/*******************************************************************************
** SQL Server database create schema scripts
** Semarchy xDM Tutorials
** Copy and paste the SQL DDL scripts and use them in the tutorial.
** Copyright (c) 2019 Semarchy
*******************************************************************************/

/******************************
Configure Database Schemas
******************************/

-- Repository
CREATE DATABASE SEMARCHY_REPOSITORY
GO
CREATE LOGIN SEMARCHY_REPOSITORY WITH  PASSWORD='SEMARCHY_REPOSITORY'
GO
USE SEMARCHY_REPOSITORY
GO
CREATE USER SEMARCHY_REPOSITORY FOR LOGIN SEMARCHY_REPOSITORY
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_REPOSITORY
GO

-- Retail MDM Data Location
CREATE DATABASE SEMARCHY_PRODUCT_RETAIL_MDM
GO
CREATE LOGIN SEMARCHY_PRODUCT_RETAIL_MDM WITH PASSWORD='SEMARCHY_PRODUCT_RETAIL_MDM'
GO
USE SEMARCHY_PRODUCT_RETAIL_MDM
GO
CREATE USER SEMARCHY_PRODUCT_RETAIL_MDM FOR LOGIN SEMARCHY_PRODUCT_RETAIL_MDM
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_PRODUCT_RETAIL_MDM
GO

-- Customer B2C Data Location
CREATE DATABASE SEMARCHY_CUSTOMER_B2C_MDM
GO
CREATE LOGIN SEMARCHY_CUSTOMER_B2C_MDM WITH PASSWORD='SEMARCHY_CUSTOMER_B2C_MDM'
GO
USE SEMARCHY_CUSTOMER_B2C_MDM
GO
CREATE USER SEMARCHY_CUSTOMER_B2C_MDM FOR LOGIN SEMARCHY_CUSTOMER_B2C_MDM
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_CUSTOMER_B2C_MDM
GO

CREATE DATABASE SEMARCHY_EMP_TUTORIAL
GO
CREATE LOGIN SEMARCHY_EMP_TUTORIAL WITH PASSWORD='SEMARCHY_EMP_TUTORIAL'
GO
USE SEMARCHY_EMP_TUTORIAL
GO
CREATE USER SEMARCHY_EMP_TUTORIAL FOR LOGIN SEMARCHY_EMP_TUTORIAL
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_EMP_TUTORIAL
GO

CREATE DATABASE SEMARCHY_B2B_TUTORIAL
GO
CREATE LOGIN SEMARCHY_B2B_TUTORIAL WITH PASSWORD='SEMARCHY_B2B_TUTORIAL'
GO
USE SEMARCHY_B2B_TUTORIAL
GO
CREATE USER SEMARCHY_B2B_TUTORIAL FOR LOGIN SEMARCHY_B2B_TUTORIAL
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_B2B_TUTORIAL
GO

/* Give SEMARCHY_CUSTOMER_B2C_MDM user read access to all the tables (and views) in semarchy_repository */
GRANT SELECT ON SEMARCHY_REPOSITORY TO SEMARCHY_CUSTOMER_B2C_MDM;
GO

/* Cleanup scripts to start fresh */
/*
  DROP DATABASE SEMARCHY_REPOSITORY
  GO
  DROP LOGIN    SEMARCHY_REPOSITORY
  GO

  DROP DATABASE SEMARCHY_PRODUCT_RETAIL_MDM
  GO
  DROP LOGIN    SEMARCHY_PRODUCT_RETAIL_MDM
  GO

  DROP DATABASE SEMARCHY_CUSTOMER_B2C_MDM
  GO
  DROP LOGIN    SEMARCHY_CUSTOMER_B2C_MDM
  GO

  DROP DATABASE SEMARCHY_EMP_TUTORIAL
  GO
  DROP LOGIN    SEMARCHY_EMP_TUTORIAL
  GO

  DROP DATABASE SEMARCHY_B2B_TUTORIAL
  GO
  DROP LOGIN    SEMARCHY_B2B_TUTORIAL
  GO
*/

/******************************************************************************/
