/*******************************************************************************
** SQL Server database create schema scripts
** Semarchy xDM Tutorials
** Copy and paste the SQL DDL scripts and use them in the tutorial.
** Copyright (c) 2019 Semarchy
*******************************************************************************/

/******************************
Configure Database Schemas
******************************/

-- Repository
CREATE DATABASE SEMARCHY_REPOSITORY
GO
CREATE LOGIN SEMARCHY_REPOSITORY WITH  PASSWORD='13BC5881-632b-12ef-cd34-1256bd302470'
GO
USE SEMARCHY_REPOSITORY
GO
CREATE USER SEMARCHY_REPOSITORY FOR LOGIN SEMARCHY_REPOSITORY
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_REPOSITORY
GO

-- Create the repository read-only user
CREATE LOGIN SEMARCHY_REPOSITORY_RO WITH PASSWORD='13BC5881-632b-12ef-cd34-1256bd302471', DEFAULT_DATABASE=SEMARCHY_REPOSITORY
GO
USE SEMARCHY_REPOSITORY
GO
CREATE USER SEMARCHY_REPOSITORY_RO FOR LOGIN SEMARCHY_REPOSITORY_RO
GO

-- Grant minimum access to the user
GRANT CONNECT TO SEMARCHY_REPOSITORY_RO;


-- Retail MDM Data Location
CREATE DATABASE SEMARCHY_PRODUCT_RETAIL_MDM
GO
CREATE LOGIN SEMARCHY_PRODUCT_RETAIL_MDM WITH PASSWORD='13BC5881-632b-12ef-cd34-1256bd302472'
GO
USE SEMARCHY_PRODUCT_RETAIL_MDM
GO
CREATE USER SEMARCHY_PRODUCT_RETAIL_MDM FOR LOGIN SEMARCHY_PRODUCT_RETAIL_MDM
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_PRODUCT_RETAIL_MDM
GO

-- Customer B2C Data Location
CREATE DATABASE SEMARCHY_CUSTOMER_B2C_MDM
GO
CREATE LOGIN SEMARCHY_CUSTOMER_B2C_MDM WITH PASSWORD='13BC5881-632b-12ef-cd34-1256bd302473'
GO
USE SEMARCHY_CUSTOMER_B2C_MDM
GO
CREATE USER SEMARCHY_CUSTOMER_B2C_MDM FOR LOGIN SEMARCHY_CUSTOMER_B2C_MDM
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_CUSTOMER_B2C_MDM
GO

-- Employee HR Tutorial - Track 1 - Data Location
CREATE DATABASE SEMARCHY_EMP_TUTORIAL
GO
CREATE LOGIN SEMARCHY_EMP_TUTORIAL WITH PASSWORD='13BC5881-632b-12ef-cd34-1256bd302474'
GO
USE SEMARCHY_EMP_TUTORIAL
GO
CREATE USER SEMARCHY_EMP_TUTORIAL FOR LOGIN SEMARCHY_EMP_TUTORIAL
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_EMP_TUTORIAL
GO

-- Customer B2B - Track 2 - Data Location
CREATE DATABASE SEMARCHY_B2B_TUTORIAL
GO
CREATE LOGIN SEMARCHY_B2B_TUTORIAL WITH PASSWORD='13BC5881-632b-12ef-cd34-1256bd302475'
GO
USE SEMARCHY_B2B_TUTORIAL
GO
CREATE USER SEMARCHY_B2B_TUTORIAL FOR LOGIN SEMARCHY_B2B_TUTORIAL
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_B2B_TUTORIAL
GO

-- Additional Data Location1
CREATE DATABASE SEMARCHY_DLOC1
GO
CREATE LOGIN SEMARCHY_DLOC1 WITH PASSWORD='13BC5881-632b-12ef-cd34-1256bd302476'
GO
USE SEMARCHY_DLOC1
GO
CREATE USER SEMARCHY_DLOC1 FOR LOGIN SEMARCHY_DLOC1
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_DLOC1
GO

-- Additional Data Location2
CREATE DATABASE SEMARCHY_DLOC2
GO
CREATE LOGIN SEMARCHY_DLOC2 WITH PASSWORD='13BC5881-632b-12ef-cd34-1256bd302477'
GO
USE SEMARCHY_DLOC2
GO
CREATE USER SEMARCHY_DLOC2 FOR LOGIN SEMARCHY_DLOC2
GO
ALTER ROLE db_owner ADD MEMBER SEMARCHY_DLOC2
GO

/* Cleanup scripts to start fresh */
/*
  DROP DATABASE SEMARCHY_REPOSITORY
  GO
  DROP LOGIN    SEMARCHY_REPOSITORY
  GO
  DROP LOGIN    SEMARCHY_REPOSITORY_RO
  GO
  DROP DATABASE SEMARCHY_PRODUCT_RETAIL_MDM
  GO
  DROP LOGIN    SEMARCHY_PRODUCT_RETAIL_MDM
  GO
  DROP DATABASE SEMARCHY_CUSTOMER_B2C_MDM
  GO
  DROP LOGIN    SEMARCHY_CUSTOMER_B2C_MDM
  GO
  DROP DATABASE SEMARCHY_EMP_TUTORIAL
  GO
  DROP LOGIN    SEMARCHY_EMP_TUTORIAL
  GO
  DROP DATABASE SEMARCHY_B2B_TUTORIAL
  GO
  DROP LOGIN    SEMARCHY_B2B_TUTORIAL
  GO
  DROP DATABASE SEMARCHY_DLOC1
  GO
  DROP LOGIN    SEMARCHY_DLOC1
  GO
  DROP DATABASE SEMARCHY_DLOC2
  GO
  DROP LOGIN    SEMARCHY_DLOC2
  GO
*/

/******************************************************************************/